config/routes.rb
ToDo::Application.routes.draw do

  match '/items/batch_update' => 'items#batch_update'

  resources :projects do
    resources :items
  end

  resources :teams do
    resources :projects, :only => [:new]
    resources :users, :only => [:new]
  end

  resources :users

  root to: "dashboard#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :desc, :is_complete, :project_id, :title
  belongs_to :project

  validates :title, :project, presence: true

  def completed?
     is_complete
   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :desc, :team_id, :title, :item_ids
  has_many :items
  belongs_to :team

  validates :team, :title, presence: true

  def completed?
    !items.empty? && items.all?(&:completed?)
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :member_ids
  has_many :team_memberships
  has_many :members, :through => :team_memberships
  has_many :projects

  validates :name, presence: true
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  attr_accessible :member_id, :team_id
  belongs_to :team
  belongs_to :member, class_name: "User"

  validates :team, :member, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :team_ids
  has_many :team_memberships, foreign_key: "member_id"
  has_many :teams, :through => :team_memberships
  has_many :projects, :through => :teams

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @projects = Project.all
    @teams = Team.all
    @users = User.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @items = Item
    @items = @items.where("project_id = ?", params[:project_id]) if params[:project_id]
    @items = @items.all
  end

  def show
    @project = Project.find(params[:project_id])
    @item = Item.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @item = Item.new
    @item.project_id = params[:project_id]
    @projects = Project.all
  end

  def edit
    @project = Project.find(params[:project_id])
    @item = Item.find(params[:id])
    @projects = Project.all
  end

  def create
    @project = Project.find(params[:project_id])
    @item = Item.create(params[:item])
    if @item.id
      redirect_to project_item_path(@project, @item)
    else
      @projects = Project.all
      render :new
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      redirect_to project_item_path(@project, @item)
    else
      @projects = Project.all
      render :edit
    end
  end

  def batch_update
    params[:items].each do |item_id, status|
      Item.find(item_id).update_attributes(status)
    end
    redirect_to :back
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = case params[:order]
    when 'a-z' then Project.order("title")
    when 'z-a' then Project.order("title DESC")
    when 'newest' then Project.order("created_at DESC")
    when 'oldest' then  Project.order("created_at ASC")
    else Project
    end
    @projects = @projects.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @project.team_id = params[:team_id]
    @teams = Team.all
  end

  def create
    @project = Project.create(params[:project])
    if @project.id
      redirect_to project_path(@project)
    else
      @teams = Team.all
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    @teams = Team.all
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to project_path(@project)
    else
      @teams = Team.all
      render :edit
    end
  end

  def batch_update
    p params
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = case params[:order]
    when 'a-z' then Team.order("name")
    when 'z-a' then Team.order("name DESC")
    when 'newest' then Team.order("created_at DESC")
    when 'oldest' then  Team.order("created_at ASC")
    else Team
    end
    @teams = @teams.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
    @users = User.all
  end

  def create
    @team = Team.create(params[:team])
    if @team.id
      redirect_to team_path(@team)
    else
      @users = User.all
      render :new
    end
  end

  def edit
    @team = Team.find(params[:id])
    @users = User.all
  end

  def update
    @team = Team.find(params[:id])
    if @team.update_attributes(params[:team])
      redirect_to team_path(@team)
    else
      @users = User.all
      render :edit
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = case params[:order]
    when 'a-z' then User.order("name")
    when 'z-a' then User.order("name DESC")
    when 'newest' then User.order("created_at DESC")
    when 'oldest' then  User.order("created_at ASC")
    else User
    end
    @users = @users.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @selected_team = params[:team_id].to_i
    @teams = Team.all
  end

  def create
    @user = User.create(params[:user])
    if @user.id
      redirect_to user_path(@user)
    else
      @teams = Team.all
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    @teams = Team.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user)
    else
      @teams = Team.all
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def breadcrumb_helper(paths)
    s = '<ul class="breadcrumb"><li><a href="/">Index</a> <span class="divider">/</span></li>'
    paths.each do |path|
      if path.last
        s += "<li><a href='#{path.last}'>#{path.first}</a> <span class='divider'>/</span></li>"
      else
        s += "<li class='active'>#{path.first}</li>"
      end
    end
    s + "</ul>"
    s.html_safe
  end

  def complete_label(complete)
    if complete
      '<span class="label label-success">Complete</span>'.html_safe
    else
      '<span class="label label-warning">Incomplete</span>'.html_safe
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def complete_hidden_tag(complete)
    if complete
      hidden_field_tag "item[is_complete]", false
    else
      hidden_field_tag "item[is_complete]", true
    end.html_safe
  end

  def complete_button(complete, f)
     if complete
       f.submit("Incomplete", class: "btn btn-warning")
     else
       f.submit("Complete", class: "btn btn-success")
     end.html_safe
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<%= breadcrumb_helper([]) %>
<legend>
  <h1>At a glance...</h1>
</legend>

<div class="row-fluid" style='text-align:center;'>
  <div class="span4">
    <legend>
      <%= link_to("Projects", projects_path) %>
    </legend>
    <table class="table table-striped table-bordered table-hover">
      <% @projects.each do |project| %>
      <tr>
        <td style='text-align:center;' onclick='window.location = "<%= project_path(project) %>"'>
          <%= link_to(project.title, project_path(project)) %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="span4">
    <legend>
      <%= link_to("Teams", teams_path) %>
    </legend>
    <table class="table table-striped table-bordered table-hover  ">
      <% @teams.each do |team| %>
      <tr>
        <td style='text-align:center;' onclick='window.location = "<%= team_path(team) %>"'>
          <%= link_to(team.name, team_path(team)) %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="span4">
    <legend>
      <%= link_to("Users", users_path) %>
    </legend>
    <table class="table table-striped table-bordered table-hover  ">
      <% @users.each do |user| %>
      <tr>
        <td style='text-align:center;' onclick='window.location = "<%= user_path(user) %>"'>
          <%= link_to(user.name, user_path(user)) %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for([@project, @item], :html => {class: "form-horizontal"}) do |f| %>
<div class="control-group <%= "error" unless @item.errors[:title].empty? %>">
<%= f.label :title, class: "control-label" %>
<div class='controls'>
<%= f.text_field :title %>
<span class="help-inline"><%= @item.errors[:title].join(", ") %></span>
</div>
</div>
<div class="control-group">
<%= f.label :project, class: "control-label" %>
<div class='controls'>
<%= f.collection_select(:project_id, @projects, :id, :title) %>
</div>
</div>
<div class="control-group">
<%= f.label :desc, "Description", class: "control-label" %>
<div class='controls'>
<%= f.text_area :desc, class: "span8", rows: 5 %>
</div>
</div>
<div class="control-group">
  <div class='controls'>
<%= f.submit :class => "btn" %>
</div>
</div>
<% end %>

app/views/items/edit.html.erb
<%= breadcrumb_helper([["Projects", projects_path], [@project.title, project_path(@project)], ["Items", project_items_path(@project)], [@item.title, project_item_path(@project, @item)], ["Edit", nil]]) %>
<legend>
  <h1>Edit Item</h1>
</legend>
<%= render :partial => "form" %>

app/views/items/index.html.erb
<%= breadcrumb_helper([["Projects", projects_path], [@project.title, project_path(@project)], ["Items", nil]]) %>
<legend>
  <h1>Items
    <small>
      <%= link_to("Add Item", new_project_item_path(@project)) %>
    </small>
  </h1>
</legend>
<ol>
<% @items.each do |item| %>
<li>
<h4>
<%= link_to(item.title, project_item_path(@project, item)) %>
<%= complete_label(item.completed?) %>
</h4>
<blockquote>
  <p><%= simple_format(item.desc) %></p>
</blockquote>
</li>
<% end %>
</ol>

app/views/items/new.html.erb
<%= breadcrumb_helper([["Projects", projects_path], [@project.title, project_path(@project)], ["Items", project_items_path(@project)], ["New", nil]]) %>
<legend>
  <h1>New Item</h1>
</legend>
<%= render :partial => "form" %>

app/views/items/show.html.erb
<%= breadcrumb_helper([["Projects", projects_path], [@project.title, project_path(@project)], ["Items", project_items_path(@project)], [@item.title, nil]]) %>
<legend>
  <h1>
    <%= @item.title %>
    <%= complete_label(@item.completed?) %>
    <small>
      <%= link_to("Edit", edit_project_item_path(@project, @item))%>
    </small>
  </h1>

  <small class='pull-right'>Item <%= @item.project.items.index(@item) + 1 %> of <%= @item.project.items.count %> in Project <%= link_to(@item.project.title, project_path(@item.project)) %></small>
</legend>

<%= form_for([@project,@item], html: {style: "display: inline"}) do |f| %>
<%= complete_hidden_tag(@item.completed?) %>
<%= complete_button(@item.completed?, f) %>
<% end %>
<h3>Description</h3>
<blockquote>
  <p>
    <%= simple_format(@item.desc) %>
    <%= "None" if @item.desc.nil? %>
  </p>
</blockquote>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container-fluid'>

    <div class='well' style='margin-top:10px;'>
      <div class="navbar">
        <div class="navbar-inner">
          <a class="brand" href="/">TodoApp</a>
          <ul class="nav">
            <li><a href="<%=projects_path%>">Projects</a></li>
            <li><a href="<%=teams_path%>">Teams</a></li>
            <li><a href="<%=users_path%>">Users</a></li>
          </ul>
        </div>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {class: "form-horizontal"}) do |f| %>
<div class="control-group <%= "error" unless @project.errors[:title].empty? %>">
  <%= f.label :title, class: "control-label" %>
  <div class="controls">
  <%= f.text_field :title %>
  <span class="help-inline"><%= @project.errors[:title].join(", ") %></span>
  </div>
</div>
<div class="control-group">
<%= f.label :team, class: "control-label" %>
  <div class="controls">
    <%= f.collection_select(:team_id, @teams, :id, :name) %>
  </div>
</div>
<div class="control-group">
<%= f.label :desc, "Description", class: "control-label" %>
  <div class="controls">
    <%= f.text_area :desc, class: "span8", rows: 5 %>
  </div>
</div>
<div class="control-group">
  <div class="controls">
    <%= f.submit :class => "btn" %>
  </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<%= breadcrumb_helper([["Projects", projects_path], [@project.title, project_path(@project)], ["Edit", nil]]) %>
<legend>
  <h1>Edit Project</h1>
</legend>
<%= render :partial => "form" %>

app/views/projects/index.html.erb
<%= breadcrumb_helper([["Projects", nil]]) %>
<legend>
  <h1>
    Projects
    <small>
      <%= link_to("Create new project", new_project_path) %>
      <br>
      Order by
      <%= link_to("title (a-z)", {:order => "a-z"}) %>
      /
      <%= link_to("title (z-a)", {:order => "z-a"}) %>
      /
      <%= link_to("newest first", {:order => "newest"}) %>
      /
      <%= link_to("oldest first", {:order => "oldest"}) %>
    </small>
  </h1>
</legend>
<% @projects.each do |project| %>
<h4>

<%= link_to(project.title, project_path(project)) %>
<%= complete_label(project.completed?) %>
</h4>
<% end %>

app/views/projects/new.html.erb
<%= breadcrumb_helper([["Projects", projects_path], ["New", nil]]) %>
<legend>
  <h1>New Project</h1>
</legend>
<%= render :partial => "form" %>

app/views/projects/show.html.erb
<%= breadcrumb_helper([["Projects", projects_path], [@project.title, nil]]) %>
<legend>
  <h1>
    Project "<%= @project.title %>"
    <%= complete_label(@project.completed?) %>
    <small>
      <%= link_to("Edit", edit_project_path(@project))%>
    </small>
  </h1>

  <small class='pull-right'><%= link_to(@project.team.name,
    team_path(@project.team)) %></small>
</legend>
<h3>
  <%= link_to("Items", project_items_path(@project)) %>
  <small>
    <%= link_to("Add Item", new_project_item_path(@project)) %>
  </small>
</h3>

<form action="<%=items_batch_update_path%>" method="POST">
<table class="table table-striped table-bordered table-hover  ">
  <tr>
    <td class='span1'> ID
    </td>
    <td> Item
    </td>
    <td class='span1'> Completed
    </td>
  </tr>
  <% @project.items.each do |item| %>
  <tr>
    <td> <%= item.id %>
    </td>
    <td>
      <%= link_to(item.title, project_item_path(@project, item)) %>
      <% if item.desc && !item.desc.chomp.strip.empty? %>
        <a class="accordion-toggle btn btn-mini pull-right"
          data-toggle="collapse" data-parent="#accordion2"
          href="#collapse<%= item.id %>">
          description
        </a>
        <div id="collapse<%= item.id %>" class="accordion-body collapse">
          <div class="accordion-inner">
            <%= simple_format(item.desc) %>
          </div>
        </div>
      <% end %>
    </td>
    <td style='text-align: center;'
      onclick='if (event.target.tagName != "INPUT") $("#is_complete_<%=item.id%>").prop("checked",
      !$("#is_complete_<%=item.id%>").prop("checked"));'>
      <%= hidden_field_tag("items[#{item.id}][is_complete]", false ) %>
      <%=
      check_box_tag(
        "items[#{item.id}][is_complete]",
        true,
        item.completed?,
        id: "is_complete_#{item.id}"
      )
      %>
    </td>
  </tr>
  <% end %>
</table>
<input type='submit' class='pull-right btn btn-info' value='Update'>
</form>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: "form-horizontal"}) do |f| %>
<div class='control-group <%= "error" unless @user.errors[:name].empty? %>'>
  <%= f.label :name, class: "control-label" %>
  <div class='controls'>
    <%= f.text_field :name %>
    <span class="help-inline"><%= @user.errors[:name].join(", ") %></span>
  </div>
</div>
<div class='control-group'>
<%= f.label :teams, class: "control-label" %>
<div class='controls'>
<% @teams.each do |team| %>
<label class="checkbox" id="team_id_<%= team.id %>">
<%=

check_box_tag(
  "user[team_ids][]",
  team.id,
  @user.team_ids.include?(team.id) || @selected_team == team.id,
  id: "user_team_id_#{team.id}"
)
%>
<%= team.name %>
</label>
<% end %>
<%= hidden_field_tag "user[team_ids][]" %>
  </div>
</div>
<div class='control-group'>
  <div class='controls'>
    <%= f.submit :class => "btn" %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= breadcrumb_helper([["Users", users_path], [@user.name, user_path(@user)], ["Edit", nil]]) %>
<legend>
  <h1>Edit User</h1>
</legend>
<%= render :partial => "form" %>

app/views/users/index.html.erb
<%= breadcrumb_helper([["Users", nil]]) %>
<legend>
  <h1>
    Users
    <small>
      <%= link_to("Create new user", new_user_path) %>
      <br>
      Order by
      <%= link_to("name (a-z)", {:order => "a-z"}) %>
      /
      <%= link_to("name (z-a)", {:order => "z-a"}) %>
      /
      <%= link_to("newest first", {:order => "newest"}) %>
      /
      <%= link_to("oldest first", {:order => "oldest"}) %>
    </small>
  </h1>
</legend>
<% @users.each do |user| %>
<h4>
<%= link_to(user.name, user_path(user)) %>
</h4>
<% end %>

app/views/users/new.html.erb
<%= breadcrumb_helper([["Users", users_path], ["New", nil]]) %>
<legend>
  <h1>New User</h1>
</legend>
<%= render :partial => "form" %>

app/views/users/show.html.erb
<%= breadcrumb_helper([["Users", users_path], [@user.name, nil]]) %>
<legend>
  <h1>
    <%= @user.name %>
    <small>
      <%= link_to("Edit", edit_user_path(@user))%>
    </small>
  </h1>
</legend>
<h3>Teams</h3>
<ul>
<% @user.teams.each do |team| %>

<li>
<%= link_to(team.name, team_path(team)) %>
</li>

<% end %>
</ul>

<h3>Projects</h3>
<ul>
<% @user.projects.each do |project| %>

<li>
<%= link_to(project.title, project_path(project)) %>
</li>

<% end %>
</ul>